name: Upload Assets

on:
  release:
    types:
      - released

jobs:
  build_and_upload:
    name: Publish for ${{ matrix.platform }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - platform: linux
            GOOS: linux
          - platform: macos
            GOOS: darwin
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.4"
      - name: Build
        run: go build -ldflags="-X 'github.com/ajschmidt8/r3/cmd.VERSION=$VERSION'"
        env:
          VERSION: ${{ github.event.release.tag_name }}
          GOOS: ${{ matrix.GOOS }}
          GOARCH: amd64
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: r3
          asset_name: r3_${{ matrix.platform }}
          tag: ${{ github.ref }}
